FROM dakkak/latex:heavy
LABEL maintainer="dakkak@illinois.edu"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy --no-install-recommends --no-install-suggests \
  texlive-full \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
